= ADR-001: We use ADRs
Sebastian Sommerfeld <sebastian@sommerfeld.io>

[cols="1,6"]
|===
|Status |Accepted
|Decision Date |2024-05-24
|Decision |Use ADRs
|===

== Context

* We want to think about all our architectural decisions, exploring all alternatives and making a careful, considered, well-researched choice.
* We want to be as transparent as possible in our decision-making process.
* We want to be able to revisit prior decisions to determine fairly if they still make sense, and if the motivating circumstances or conditions have changed.

== Decision

We will document every architecture-level decision an
link:http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Architecture Decision Record]. These are a well structured, relatively lightweight way to capture architectural proposals. They can serve as an artifact for discussion, and remain as an enduring record of the context and motivation of past decisions.

The workflow will be:

. A developer creates an ADR document outlining an approach for a particular question or problem. The ADR has an initial status of "proposed."
. The developers discuss the ADR. During this period, the ADR should be updated to reflect additional context, concerns raised, and proposed changes.
. Once consensus is reached, ADR can be transitioned to either an "accepted" or "rejected" state.
. Only after an ADR is accepted should implementing code be committed to the main branch of the relevant project/module.
.. If a decision is revisited and a different conclusion is reached, a new ADR should be created documenting the context and rationale for the change. The new ADR should reference the old one, and once the new one is accepted, the old one should (in its "status" section) be updated to point to the new one. The old ADR should not be removed or otherwise modified except for the annotation pointing to the new ADR.

== Consequences

. Developers must write an ADR and submit it for review before selecting an approach to any architectural decision -- that is, any decision that affects the way krokidile application is put together at a high level.
. We will have a concrete artifact around which to focus discussion, before finalizing decisions.
. If we follow the process, decisions will be made deliberately, as a group.
. We will have a useful persistent record of why the system is the way it is.
