---
ls:
  .adoc: kebab-case | SCREAMING_SNAKE_CASE | PascalCase
  .puml: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE

  .conf: kebab-case
  .go: snake_case
  .json: kebab-case
  .rb: kebab-case
  .tf: kebab-case
  .yml: kebab-case
  .yaml: kebab-case
  .feature: kebab-case

  .java: PascalCase
  .kt: PascalCase
  .sh: kebab-case

  .css: kebab-case
  .html: kebab-case
  .js: kebab-case
  .hbs: kebab-case
  .svg: kebab-case

  Dockerfile: PascalCase
  Vagrantfile: PascalCase

  .babelrc: lowercase
  .env: lowercase
  .dockerignore: lowercase
  .folderslintrc: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase
  .shellcheckrc: lowercase

ignore:
  - dist
  - docs/ui-bundle/.gulp.json
  - docs/ui-bundle/src/js/vendor/highlight.bundle.js

  # commons
  - .git
  - .idea
  - .vscode
  - node_modules
  - .gitpod.yml
  - target

  # linter definitions etc.
  - .hadolint.yml
  - .ls-lint.yml
  - .yamllint.yml
  - .prettierrc
  - commitlint.config.js
  - release.config.js
  - webpack.config.js
