---
## This Docker Compose file handles three responsibilities:
##
## . Linting the project files to ensure they adhere to coding standards.
## . Building the krokidile application.
## . Testing the application.
##
## When running docker-compose up, all services are orchestrated to execute sequentially, ensuring
## the project is linted, built, and tested efficiently within the Docker environment.
##
## [source, bash]
## ....
## docker compose build
## docker compose up
## ....

services:
  lint-yaml:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-yaml
    image: cytopia/yamllint:latest
    volumes:
      - .:/workspaces/krokidile
    working_dir: /workspaces/krokidile
    command: .
    tty: true

  lint-filenames:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-filenames
    image: lslintorg/ls-lint:1.11.2
    volumes:
      - .:/workspaces/krokidile
    working_dir: /workspaces/krokidile

  lint-folders:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-folders
    image: sommerfeldio/folderslint:latest
    volumes:
      - .:/workspaces/krokidile
    working_dir: /workspaces/krokidile
    command: .
    tty: true

  lint-dockerfile-app:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-dockerfile-app
    image: hadolint/hadolint:latest
    volumes:
      - .:/workspaces/krokidile
    working_dir: /workspaces/krokidile
    entrypoint: hadolint Dockerfile.app

  lint-dockerfile-docs:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-dockerfile-docs
    image: hadolint/hadolint:latest
    volumes:
      - .:/workspaces/krokidile
    working_dir: /workspaces/krokidile
    entrypoint: hadolint Dockerfile.docs

  kroki:
    container_name: ${COMPOSE_PROJECT_NAME}-kroki
    image: yuzutech/kroki:0.25.0
    ports:
      - 3001:8000
    depends_on:
      - lint-dockerfile-app
      - lint-filenames
      - lint-folders
      - lint-yaml

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: local/${COMPOSE_PROJECT_NAME}:${DEV_TAG}
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:9000
    environment:
      - KROKI_URL=http://kroki:3001
    depends_on:
      - kroki

  docs:
    container_name: ${COMPOSE_PROJECT_NAME}-docs
    image: local/${COMPOSE_PROJECT_NAME}-docs:${DEV_TAG}
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - 3080:3000
    depends_on:
      - lint-dockerfile-docs
      - lint-filenames
      - lint-folders
      - lint-yaml
