= Contribute to this Project
Sebastian Sommerfeld <sebastian@sommerfeld.io>

== Code
We're thrilled that you'd like to contribute to this project. You can do this by submitting a pull request.

. Take a look at our xref:development-guide:development-guide.adoc[] to get an idea of how we work
. Fork and clone the repository
. Create a new branch: git checkout -b my-branch-name
. Make your changes and include tests (preferably by using TDD)
. Make sure the tests pass
. Format code and build artifacts
. Push to your fork and submit a pull request
. Pat your self on the back and wait for your pull request to be reviewed and merged

Here are a few things you can do that will increase the likelihood of your pull request being accepted:

. Write tests
. Make sure the documentation (docs folder) and any other relevant documentation are kept up-to-date
. We try to follow SemVer v2.0.0 so randomly breaking public APIs is not an option
. Keep your change as focused as possible - If there are multiple changes you would like to make that are not dependent upon each other, consider submitting them as separate pull requests
. Write a link:https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[good commit message]

== Bug Reports
We'd love to hear your feedback on this project. Please feel free to submit an issue explaining your feature request. We're also open to ideas and suggestions for improvements.

To increase the likelihood of your feature request being accepted, please write your request in the form of a user story and add some acceptance criteria (which ideally can be turned into automated tests).

== Feature Requests
We'd love to hear your feedback on this project. Please feel free to submit an issue explaining your feature request. We're also open to ideas and suggestions for improvements.

To increase the likelihood of your feature request being accepted, please write your request in the form of a user story and add some acceptance criteria (which ideally can be turned into automated tests).
