= krokidile
Sebastian Sommerfeld <sebastian@sommerfeld.io>
:github-org: sommerfeld-io
:project-name: krokidile
:url-project: https://github.com/{github-org}/{project-name}
:github-actions-url: {url-project}/actions/workflows
:job: pipeline.yml
:badge: badge.svg

Krokidile is a web-based Live-Editor for Diagrams to use with link:https://kroki.io[Kroki.io].

image:{github-actions-url}/{job}/{badge}[Github Badge, link={github-actions-url}/{job}]

* Github Repository -> {url-project}
* DockerHub -> https://hub.docker.com/r/sommerfeldio/{project-name}
* Where to file issues -> {url-project}/issues

This project is a web-based live editor for diagrams, enabling developers to see a real-time preview of their diagrams as they write the diagram code. This immediate feedback loop makes it easier to create and modify diagrams, as developers can instantly see the impact of their changes.

Diagrams are rendered with Kroki. Kroki is a tool that renders diagrams from code allowing developers to write diagrams as code.

The main advantage of using diagrams as code is that it allows for version control, collaboration, and automation, just like any other piece of code in your repository

krokidile provides a web-based live editor for diagrams, enabling developers to see a real-time preview of their diagrams as they write the code. This immediate feedback loop makes it easier to create and modify diagrams, as developers can instantly see the impact of their changes.

== Features
* Real-time preview of diagrams based on diagram code
* Support for multiple diagram types (see https://kroki.io)
* Export diagrams as images or SVG
* Configure krokidile to use your own Kroki instance (e.g., for self-hosting or to ensure your diagram data is kept private)

== How to use this project
[source, bash]
----
docker run --rm -p 3000:3000 -e KROKI_URL=https://kroki.io sommerfeldio/krokidile:latest
----

[source, yml]
----
services:
  kroki:
    container_name: kroki
    image: yuzutech/kroki:0.25.0
    ports:
      - 3001:8000
  krokidile:
    container_name: krokidile
    image: sommerfeldio/krokidile:latest
    environment:
      - KROKI_URL=http://kroki:8000
    ports:
      - 3000:3000
    depends_on:
      - kroki
----

== Risks and Technical Debts
link:{url-project}/issues?q=is%3Aissue+label%3Asecurity%2Crisk+is%3Aopen[All issues labeled as risk (= some sort of risk or a technical debt) or security (= related to security issues)] are tracked as Github issue and carry the respective label.

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
