= Introduction
Sebastian Sommerfeld <sebastian@sommerfeld.io>
:github-org: sommerfeld-io
:project-name: krokidile
:url-project: https://github.com/{github-org}/{project-name}
:github-actions-url: {url-project}/actions/workflows
:job: pipeline.yml
:badge: badge.svg

Krokidile is a web-based Live-Editor for Diagrams to use with link:https://kroki.io[Kroki.io].

image:{github-actions-url}/{job}/{badge}[Github Badge, link={github-actions-url}/{job}]

* Github Repository -> {url-project}
* DockerHub -> https://hub.docker.com/r/sommerfeldio/{project-name}
* Where to file issues -> {url-project}/issues

This project is a web-based live editor for diagrams, enabling developers to see a real-time preview of their diagrams as they write the diagram code. This immediate feedback loop makes it easier to create and modify diagrams, as developers can instantly see the impact of their changes.

Diagrams are rendered with Kroki. Kroki is a tool that renders diagrams from code allowing developers to write diagrams as code.

The main advantage of using diagrams as code is that it allows for version control, collaboration, and automation, just like any other piece of code in your repository

krokidile provides a web-based live editor for diagrams, enabling developers to see a real-time preview of their diagrams as they write the code. This immediate feedback loop makes it easier to create and modify diagrams, as developers can instantly see the impact of their changes.

== Features
* Real-time preview of diagrams based on diagram code
* Support for multiple diagram types (see https://kroki.io)
* Export diagrams as PNG or SVG image
* Configure krokidile to use your own Kroki instance (e.g., for self-hosting or to ensure your diagram data is kept private)

== How to use
=== krokidile
The only way to use krokidile is to use the Docker image. The Docker image is available on Docker Hub at https://hub.docker.com/r/sommerfeldio/krokidile.
[source, bash]
----
docker run --rm -p 3000:3000 -e KROKI_URL=https://kroki.io sommerfeldio/krokidile:latest
----

This Docker compose stack starts a kroki instance and krokidile. The krokidile instance is configured to use the kroki instance. The Environment variable `KROKI_URL` is mandatory, there is no default value.
[source, yml]
----
services:
  kroki:
    container_name: kroki
    image: yuzutech/kroki:0.25.0
    ports:
      - 3001:8000
  krokidile:
    container_name: krokidile
    image: sommerfeldio/krokidile:latest
    environment:
      - KROKI_URL=http://kroki:3001
    ports:
      - 3000:3000
    depends_on:
      - kroki
----

=== krokidile-docs
This project also publishes a documentation container. The documentation container is available on Docker Hub at https://hub.docker.com/r/sommerfeldio/krokidile-docs.

Start with plain Docker:
[source, bash]
----
docker run --rm -p 3000:3000 sommerfeldio/krokidile-docs:latest
----

This Docker compose stack starts a krokidile-docs instance. 
[source, yml]
----
services:
  docs:
    container_name: krokidile-docs
    image: sommerfeldio/krokidile-docs:latest
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - 3000:3000
----

== How to Development
Consider the following steps to start developing on this project:

. Read the xref:development-guide.adoc[].
. Prepare the node environment with `npm install`.
. Start the development server with the following command: `npm run dev`. Keep in mind that the development server is not connected to a Kroki instance and will not render diagrams. To render diagrams, start Krokidile from its docker-compose stack.

The whole Docker stack can be built and started with `docker compose build && docker compose up`.

To use the DevContainer, open the project in VSCode and select "Reopen in Container" from the command palette. Having Visual Studio Code (VSCode) and the Dev Container plugin installed are essential prerequisites for this development environment. Docker, of course, is also mandatory.

=== Components
The Application consists of the following components:

[plantuml, puml-build-image, svg]
----
@startuml

skinparam linetype ortho
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor transparent
skinparam activity {
    'FontName Ubuntu
    FontName Roboto
}

actor User

rectangle dc as "Docker Compose Stack" {
    component App <<Node>> {
        control cors as "CORS Proxy" <<App Config>>
        rectangle Frontend <<React>>
    }
    component Kroki
    component Docs <<Antora>>
}



User -right-> Frontend
Frontend -down-> cors
cors -right-> Kroki

User -right-> Docs
Docs -[hidden]down-> App

@enduml
----

The Docker Compose stacks from this repo feature some additional components that are not part of the application itself but are required to run some linting tasks etc. Because they are not part of the actual application, they are not listed here.

== Risks and Technical Debts
link:{url-project}/issues?q=is%3Aissue+label%3Asecurity%2Crisk+is%3Aopen[All issues labeled as risk (= some sort of risk or a technical debt) or security (= related to security issues)] are tracked as Github issue and carry the respective label.

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
