= MIT License

Copyright (c) 2024 sommerfeld-io

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

== Excluded from MIT License
* The UI Bundle located under `docs/ui-bundle` is used to render a documentation website on https://krokidile.sommerfeld.io. This UI bundle is NOT part of the Software and hence not licensed under the MIT License.
* The website configuration located under `docs/config` is part of the website and hence also NOT licensed under the MIT License.
* The project config on GitHub uses secrets which are used to upload Docker Images to DockerHub and upload the documentation website to https://krokidile.sommerfeld.io (among others). The GitHub secrets are NOT part of the Software and hence not licensed under the MIT License.

These listed components are not part of the Software and hence not licensed under the MIT License. They are proprietary and may not be used without the explicit permission of the author.

However the documentation itself located under `docs/modules` is part of the Software and hence licensed under the MIT License.
