---
site:
  title: krokidile
  url: /
  start_page: public::index.adoc
  robots: allow

content:
  # branches: ['*', '!dependabot/*']
  sources:
    - url: /workspaces/krokidile
      branches: ['main']
      start_path: docs
    - url: https://github.com/sommerfeld-io/krokidile.git
      branches: ~
      tags: ['v*', '!v0.0.*', '!v0.1.*', '!v0.2.*']
      start_path: docs

asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki

antora:
  extensions:
    - require: '@antora/lunr-extension'
      enabled: true
      index_latest_only: true
      snippet_length: 160

ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: /workspaces/krokidile/docs/ui-bundle/build/ui-bundle.zip
    snapshot: true

output:
  clean: true
  dir: /workspaces/krokidile/target/public

runtime:
  cache_dir: /workspaces/krokidile/target/cache/antora
  fetch: true
