---
##
##
##

name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    # TODO if main and not dependabot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Info - files to be bumped (see .versionrc.json)
        run: cat docs/antora.yml
        shell: bash
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.2.0
      - name: standard-version - Install
        run: npm install --save-dev standard-version
        shell: bash
      - name: standard-version - Run to determine the version and create a tag
        run: npx standard-version 
        shell: bash
      - name: Info - git tags
        run: git tag
        shell: bash
      - name: Info - bumped files (see .versionrc.json)
        run: cat docs/antora.yml
        shell: bash
      # - name: GitHub release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO_AND_PROJECT }}
      #   run: |
      #     git push --follow-tags
      #     VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
      #     gh release create $VERSION --generate-notes
      #   shell: bash
      # TODO revert antora.yml from bash (sed)

  # TODO dockerhub in a matrix
  