---
##
##
##

name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    # TODO if main and not dependabot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Info - package.json
        run: cat package.json
        shell: bash
      - name: Info - docs/antora.yml
        run: cat docs/antora.yml
        shell: bash
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.2.0
      - name: semantic-release - Install
        run: |
          npm install --save-dev semantic-release
          npm install --save-dev @semantic-release/commit-analyzer
          npm install --save-dev @semantic-release/release-notes-generator
          npm install --save-dev @semantic-release/github.
        shell: bash
      - name: semantic-release - Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        shell: bash

  # bump versions
  # Github release
    
  # TODO dockerhub in a matrix
  # TODO revert version in antora.yml? from bash (sed)?
